### ISSUE TITLE
Error implemeting clustersql

### ISSUE THREAD

**Issue by dreh23** [benthor/clustersql#3]
I fail to implement clustersql. 

```
 ./cluster_test.go:68: cannot use mysql.MySQLDriver literal (type mysql.MySQLDriver) as type driver.Driver in argument to NewDriver:
mysql.MySQLDriver does not implement driver.Driver (Open method has pointer receiver
```

go version go1.5rc1 linux/amd64
go version go1.3.3 linux/amd64

**Comment by benthor** [comment]
The only explanation that comes to mind is that you may have an outdated mysql driver package.

Do `go get -v -u -t github.com/benthor/clustersql` and then `go test github.com/benthor/clustersql`.
Note: in order to run the test successfully, you need three local instances of mysql/mariadb set up as a galera cluster. See the travis file in this repo for an example of how one can set this up.
